/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  ExecutableScript,
  ExecuteScriptParams,
  ExecuteScriptResult,
  Script,
  SignerProvider,
  HexString,
} from "@alephium/web3";
import { getContractByCodeHash } from "./contracts";
import { default as CheckSubmissionScriptJson } from "../CheckSubmission.ral.json";
import { default as EndContestScriptJson } from "../EndContest.ral.json";
import { default as JudgeMemeScriptJson } from "../JudgeMeme.ral.json";
import { default as SubmitMemeScriptJson } from "../SubmitMeme.ral.json";
import { MemeSubmission, AllStructs } from "./types";

export const CheckSubmission = new ExecutableScript<{
  contest: HexString;
  creator: Address;
  index: bigint;
}>(
  Script.fromJson(CheckSubmissionScriptJson, "", AllStructs),
  getContractByCodeHash
);

export const EndContest = new ExecutableScript<{ contest: HexString }>(
  Script.fromJson(EndContestScriptJson, "", AllStructs),
  getContractByCodeHash
);

export const JudgeMeme = new ExecutableScript<{
  contest: HexString;
  submitter: Address;
  index: bigint;
  aiScore: bigint;
}>(Script.fromJson(JudgeMemeScriptJson, "", AllStructs), getContractByCodeHash);

export const SubmitMeme = new ExecutableScript<{
  contest: HexString;
  memeHash: HexString;
}>(
  Script.fromJson(SubmitMemeScriptJson, "", AllStructs),
  getContractByCodeHash
);
