/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as DephiumContractJson } from "../Dephium.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";

// Custom types for the contract
export namespace DephiumTypes {
  export type Fields = {
    symbol: HexString;
    name: HexString;
    decimals: bigint;
    supply: bigint;
    balance: bigint;
    ownerAddress: Address;
  };

  export type State = ContractState<Fields>;

  export type IssueEvent = ContractEvent<{ to: Address; amount: bigint }>;

  export interface CallMethodTable {
    getSymbol: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getName: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getDecimals: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getTotalSupply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    balance: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    issueDephiumCoin: {
      params: CallContractParams<{ amount: bigint }>;
      result: CallContractResult<null>;
    };
    transfer: {
      params: CallContractParams<{ amount: bigint; win: boolean }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    getSymbol: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getName: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getDecimals: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getTotalSupply: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    balance: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    issueDephiumCoin: {
      params: SignExecuteContractMethodParams<{ amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    transfer: {
      params: SignExecuteContractMethodParams<{ amount: bigint; win: boolean }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<DephiumInstance, DephiumTypes.Fields> {
  encodeFields(fields: DephiumTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      []
    );
  }

  eventIndex = { Issue: 0 };

  at(address: string): DephiumInstance {
    return new DephiumInstance(address);
  }

  tests = {
    getSymbol: async (
      params: Omit<
        TestContractParamsWithoutMaps<DephiumTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getSymbol", params, getContractByCodeHash);
    },
    getName: async (
      params: Omit<
        TestContractParamsWithoutMaps<DephiumTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getName", params, getContractByCodeHash);
    },
    getDecimals: async (
      params: Omit<
        TestContractParamsWithoutMaps<DephiumTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getDecimals", params, getContractByCodeHash);
    },
    getTotalSupply: async (
      params: Omit<
        TestContractParamsWithoutMaps<DephiumTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getTotalSupply", params, getContractByCodeHash);
    },
    balance: async (
      params: Omit<
        TestContractParamsWithoutMaps<DephiumTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "balance", params, getContractByCodeHash);
    },
    issueDephiumCoin: async (
      params: TestContractParamsWithoutMaps<
        DephiumTypes.Fields,
        { amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "issueDephiumCoin",
        params,
        getContractByCodeHash
      );
    },
    transfer: async (
      params: TestContractParamsWithoutMaps<
        DephiumTypes.Fields,
        { amount: bigint; win: boolean }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "transfer", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: DephiumTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const Dephium = new Factory(
  Contract.fromJson(
    DephiumContractJson,
    "=20-2+9c=2-1=1+9=110-2+12=10+a0007e02175468652063757272656e742062616c616e63652069732000ce047e021754686520616d6f756e7420746f20697373756520697320007e0111616d6f756e74207472616e736665726564=92",
    "e1ab97d7acfdf75352daec3b78516bfc7f49c25871e5602af82929d6cbf78838",
    []
  )
);
registerContract(Dephium);

// Use this class to interact with the blockchain
export class DephiumInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<DephiumTypes.State> {
    return fetchContractState(Dephium, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeIssueEvent(
    options: EventSubscribeOptions<DephiumTypes.IssueEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      Dephium.contract,
      this,
      options,
      "Issue",
      fromCount
    );
  }

  view = {
    getSymbol: async (
      params?: DephiumTypes.CallMethodParams<"getSymbol">
    ): Promise<DephiumTypes.CallMethodResult<"getSymbol">> => {
      return callMethod(
        Dephium,
        this,
        "getSymbol",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getName: async (
      params?: DephiumTypes.CallMethodParams<"getName">
    ): Promise<DephiumTypes.CallMethodResult<"getName">> => {
      return callMethod(
        Dephium,
        this,
        "getName",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getDecimals: async (
      params?: DephiumTypes.CallMethodParams<"getDecimals">
    ): Promise<DephiumTypes.CallMethodResult<"getDecimals">> => {
      return callMethod(
        Dephium,
        this,
        "getDecimals",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getTotalSupply: async (
      params?: DephiumTypes.CallMethodParams<"getTotalSupply">
    ): Promise<DephiumTypes.CallMethodResult<"getTotalSupply">> => {
      return callMethod(
        Dephium,
        this,
        "getTotalSupply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    balance: async (
      params?: DephiumTypes.CallMethodParams<"balance">
    ): Promise<DephiumTypes.CallMethodResult<"balance">> => {
      return callMethod(
        Dephium,
        this,
        "balance",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    issueDephiumCoin: async (
      params: DephiumTypes.CallMethodParams<"issueDephiumCoin">
    ): Promise<DephiumTypes.CallMethodResult<"issueDephiumCoin">> => {
      return callMethod(
        Dephium,
        this,
        "issueDephiumCoin",
        params,
        getContractByCodeHash
      );
    },
    transfer: async (
      params: DephiumTypes.CallMethodParams<"transfer">
    ): Promise<DephiumTypes.CallMethodResult<"transfer">> => {
      return callMethod(
        Dephium,
        this,
        "transfer",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    getSymbol: async (
      params: DephiumTypes.SignExecuteMethodParams<"getSymbol">
    ): Promise<DephiumTypes.SignExecuteMethodResult<"getSymbol">> => {
      return signExecuteMethod(Dephium, this, "getSymbol", params);
    },
    getName: async (
      params: DephiumTypes.SignExecuteMethodParams<"getName">
    ): Promise<DephiumTypes.SignExecuteMethodResult<"getName">> => {
      return signExecuteMethod(Dephium, this, "getName", params);
    },
    getDecimals: async (
      params: DephiumTypes.SignExecuteMethodParams<"getDecimals">
    ): Promise<DephiumTypes.SignExecuteMethodResult<"getDecimals">> => {
      return signExecuteMethod(Dephium, this, "getDecimals", params);
    },
    getTotalSupply: async (
      params: DephiumTypes.SignExecuteMethodParams<"getTotalSupply">
    ): Promise<DephiumTypes.SignExecuteMethodResult<"getTotalSupply">> => {
      return signExecuteMethod(Dephium, this, "getTotalSupply", params);
    },
    balance: async (
      params: DephiumTypes.SignExecuteMethodParams<"balance">
    ): Promise<DephiumTypes.SignExecuteMethodResult<"balance">> => {
      return signExecuteMethod(Dephium, this, "balance", params);
    },
    issueDephiumCoin: async (
      params: DephiumTypes.SignExecuteMethodParams<"issueDephiumCoin">
    ): Promise<DephiumTypes.SignExecuteMethodResult<"issueDephiumCoin">> => {
      return signExecuteMethod(Dephium, this, "issueDephiumCoin", params);
    },
    transfer: async (
      params: DephiumTypes.SignExecuteMethodParams<"transfer">
    ): Promise<DephiumTypes.SignExecuteMethodResult<"transfer">> => {
      return signExecuteMethod(Dephium, this, "transfer", params);
    },
  };

  async multicall<Calls extends DephiumTypes.MultiCallParams>(
    calls: Calls
  ): Promise<DephiumTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends DephiumTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<DephiumTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends DephiumTypes.MultiCallParams | DephiumTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(Dephium, this, callss, getContractByCodeHash);
  }
}
