/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  ExecutableScript,
  ExecuteScriptParams,
  ExecuteScriptResult,
  Script,
  SignerProvider,
  HexString,
} from "@alephium/web3";
import { getContractByCodeHash } from "./contracts";
import { default as NewBidScriptJson } from "../NewBid.ral.json";

export const NewBid = new ExecutableScript<{
  auction: HexString;
  win: bigint;
  amountWagered: bigint;
}>(Script.fromJson(NewBidScriptJson, "", []), getContractByCodeHash);
